hooks_enabled=true

[model]
name="openrouter/owl-alpha"
temperature=0

[[hooks]]
name='before_agent_hook'
trigger='before_agent'
command = 'python src/scripts/test_tool.py' 

[[hooks]]
name='after_agent_hook'
trigger='after_agent'
command = 'python src/scripts/test_tool.py' 

[[hooks]]
name='before_llm_hook'
trigger='before_llm'
command = 'python src/scripts/test_tool.py' 

[[hooks]]
name='after_llm_hook'
trigger='after_llm'
command = 'python src/scripts/test_tool.py' 

[[hooks]]
name='before_tool_hook'
trigger='before_tool'
command = 'python src/scripts/test_tool.py' 

[[hooks]]
name='after_tool_hook'
trigger='after_tool'
command = 'python src/scripts/test_tool.py' 



# [mcp_servers.filesystem]
# command = "npx"
# args = ["-y", "@modelcontextprotocol/server-filesystem", "/Users/nbest/Desktop/cc-mimic/.ai-agent", "/tmp"]

# [mcp_servers.filesystem2]
# command = "npx"
# args = ["-y", "@modelcontextprotocol/server-filesystem222222222222", "/Users/nbest/Desktop/cc-mimic/.ai-agent", "/tmp"]