# initial config dir

hooks_enabled=true

# Object
[model]
name="tencent/hy3:free"
temperature=0

# List of Object
[[hooks]]
name='log_before_agent_hook'
trigger='before_agent'
command = 'python .ai-agent/hooks/test_hook.py' 

[[hooks]]
name='log_after_agent_hook'
trigger='after_agent'
command = 'python .ai-agent/hooks/test_hook.py' 

[[hooks]]
name='log_before_llm_hook'
trigger='before_llm'
command = 'python .ai-agent/hooks/test_hook.py' 

[[hooks]]
name='log_after_llm_hook'
trigger='after_llm'
command = 'python .ai-agent/hooks/test_hook.py' 

[[hooks]]
name='log_before_tool_hook'
trigger='before_tool'
command = 'python .ai-agent/hooks/test_hook.py' 

[[hooks]]
name='log_after_tool_hook'
trigger='after_tool'
command = 'python .ai-agent/hooks/test_hook.py' 

[mcp_servers.playwright]
command = "npx"
args = ["-y", "@playwright/mcp@latest"]


# [mcp_servers.filesystem]
# command = "npx"
# args = ["-y", "@modelcontextprotocol/server-filesystem", "/Users/nbest/Desktop/cc-mimic/.ai-agent", "/tmp"]

# [mcp_servers.github]
# command = "npx"
# args = ["-y", "@modelcontextprotocol/server-github"]
# env = { GITHUB_PERSONAL_ACCESS_TOKEN = "your_token" }
